# check below links for reference
# https://github.community/t/workflow-context-when-triggered-by-issue-comment/16570 
# https://github.com/Khan/pull-request-comment-trigger

#NOTES: we are using a package which compares the trigger phrases, check above link for more info on package
# once trigger phrase matches, we have to make a Github API call to get the Pull_request and extract the branch name to update git_ref 
# finally, run the script which trigger circle ci API 

name: Push Strings to Strings Repo
on:
  push:
    branches:
      - develop

jobs:
  trigger_qa_build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run Custom Commands
        run: |
        
          cd $GITHUB_WORKSPACE
          
          echo git branch
          
          git config --global user.name 'satishgarlapati'
          git config --global user.email 'satishreddyg@outlook.com'
          
          echo ${{ github.event.pull_request.head.sha }}
          
          cd ./../ && git clone https://github.com/cognosos/RadioTraxIOS.git
          
          cd $GITHUB_WORKSPACE
          
          cp ./../RadioTraxIOS/Cognosos/Extensions/UIViewController+Extension.swift ./
          
          git add .
          
          git commit -m "replacing the file"
          
          git push https://github.com/satishreddyg/TestGithubAction.git

